gui:
  theme:
    activeBorderColor:
      - '#cba6f7'
      - bold
    inactiveBorderColor:
      - '#313244'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#94e2d5'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
  showFileTree: true
  showRandomTip: false
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  
notARepository: 'skip'

os:
  editPreset: 'nvim'
